# Generated by Django 2.2 on 2020-07-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'masculino'), ('feminino', 'feminino')], max_length=9),
        ),
    ]
