# Generated by Django 2.2 on 2020-07-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200725_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='cid_est',
        ),
        migrations.AddField(
            model_name='endereco',
            name='cid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='est',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
