# Generated by Django 2.2 on 2020-07-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200726_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='n_doc',
            field=models.CharField(max_length=14),
        ),
    ]
